server:
  forward-headers-strategy: framework
spring:
  main:
    lazy-initialization: true
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy
  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}
logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
